# generated by datamodel-codegen:
#   filename:  client-keys.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Scope(StrEnum):
    install = 'install'
    standalone = 'standalone'


class AllowedModel(RootModel[str]):
    root: str = Field(..., max_length=256, min_length=1)


class AllowedTool(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class ClientKeyLimits(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    localOnly: bool | None = Field(
        False,
        description='Permit only backends explicitly classified local by drivers enforcing\nthe local-only request policy. External, unknown and older drivers\nare ineligible, including through aliases, fallback and wake. The\ncaller cannot relax this restriction. Local is a configured trust\nboundary, not a promise to sandbox a malicious backend.\n',
    )
    allowedModels: list[AllowedModel] | None = Field(
        None,
        description="Null permits all. Empty permits none. Both the id the caller\nasked for and every model actually tried (a slot's fallback\ntargets) must be allowed.\n\nAn entry is an exact id, or a pattern with `*` (P1,\n2026-09-27): `*` matches any run of characters, `/` included,\nand is the only wildcard, so `openrouter/*` allows every\nmodel of the account named `openrouter`\n(`openrouter/anthropic/claude-opus-5.5`) and nothing else.\nWithout it, scoping a key to one account means typing out\nhundreds of names. The same matcher runs in the gateway, the\nagent and the control root.\n",
        max_length=100,
    )
    allowedTools: list[AllowedTool] | None = Field(
        None,
        description='The tools the hub runs itself (P8) that this key may have run\non its behalf -- `web_search` today. **Null permits every tool\nthe install runs** (design call #5: a key is allowed search once\na search account exists, and can be denied it here). Empty\npermits none. An entry is a tool name or a pattern with `*`,\nmatched by the same matcher as `allowedModels`.\n\nA key denied a tool is not refused for asking: the door says\nwhy the search did not run, as it does for an install with no\nsearch account (`gateway.yaml`, "Server-run tools"). A\n`localOnly` key never has a tool run whatever this says,\nbecause a search sends a query derived from the prompt to the\npublic internet.\n',
        max_length=100,
    )
    writeLogs: bool | None = Field(
        False,
        description="Whether this key may send log records to an agent's log ingress\n(`POST /v1/logs` on `agent.yaml`, C1 in `workbench.md`). It\ngrants nothing else: reading logs stays operator-only.\n\nEvery app the registry installs gets a key with this on,\nbecause the launcher that runs an app in its own account\nforwards what the app prints. Any other key gets it when the\noperator turns it on, so a tool outside the registry sends its\nlogs the same way ours do.\n",
    )
    maxConcurrentRequests: int | None = Field(2, ge=1, le=64)
    requestsPerMinute: int | None = Field(60, ge=1, le=10000)


class ClientKeyUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limits: ClientKeyLimits


class Action(StrEnum):
    check = 'check'
    acquire = 'acquire'
    renew = 'renew'
    release = 'release'


class ClientAdmissionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: Action
    keyId: str = Field(..., max_length=128, min_length=1)
    requestId: str = Field(..., max_length=128, min_length=1)
    model: str | None = Field(None, max_length=256, min_length=1)


class ClientAdmissionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    keyId: str
    keyName: str
    limits: ClientKeyLimits | None = None
    leaseSeconds: float | None = Field(None, gt=0.0, le=30.0)


class ClientKeyPolicyEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., max_length=128, min_length=1)
    expiresAt: AwareDatetime
    revokedAt: AwareDatetime | None = None


class ClientKeyPolicy(BaseModel):
    """
    Positive registry: only listed, unrevoked, unexpired identifiers may be
    authorized. Default refresh 15 seconds, maximum age 60 seconds (up to
    five seconds clock tolerance). Missing/stale policy causes client-only
    503; known revoked keys remain refused. Operator/service auth is unaffected.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    authority: str = Field(..., min_length=1)
    revision: int = Field(..., ge=0)
    generatedAt: float = Field(
        ...,
        description='Authority UTC Unix timestamp. Intermediaries must not renew it.',
    )
    keys: list[ClientKeyPolicyEntry]


class ClientKey(BaseModel):
    id: str = Field(..., max_length=128, min_length=1)
    name: str = Field(..., max_length=64, min_length=1)
    tail: str = Field(..., max_length=6)
    createdAt: AwareDatetime
    expiresAt: AwareDatetime
    revokedAt: AwareDatetime | None = None
    lastUsedAt: AwareDatetime | None = Field(
        None, description='Reserved; not currently measured.'
    )
    limits: ClientKeyLimits | None = Field(
        None,
        description='Absent on legacy keys (all models, no per-key limits); new keys receive bounded defaults.',
    )


class ClientKeyList(BaseModel):
    keys: list[ClientKey]
    authority: str | None = None
    revision: int | None = Field(None, ge=0)
    scope: Scope | None = None
    detail: str | None = None


class ClientKeyCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=64, min_length=1)
    ttlDays: int | None = Field(365, ge=1, le=3650)
    limits: ClientKeyLimits | None = None


class ClientKeyCreated(BaseModel):
    key: ClientKey
    token: str = Field(
        ...,
        description='Returned once; never persisted in the registry or gateway cache.',
    )
