# generated by datamodel-codegen:
#   filename:  gateway.yaml

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class DriverProbeRequest(BaseModel):
    """
    Request body for `POST /v1/admin/drivers/probe`. Tests a single
    backend URL without persisting it. A driver slot in the
    gateway's `drivers` config may name several backends, as
    topology entry names; the UI resolves each to a URL and probes
    them separately so an operator can verify every fallback before
    saving.

    """

    url: AnyUrl = Field(..., description='The single backend base URL to test-connect.')
    name: str | None = Field(
        None,
        description='Optional slot label, echoed into diagnostics. Not required\nto probe; the operator may be testing a URL before naming\nthe slot.\n',
    )


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str | None = Field(
        None,
        description='Message text. Text-only for now; multimodal extensions\ndeferred. **Nullable, and no longer required:** an assistant\nturn that only calls a tool has no text to carry, and the\nalternative — an empty string — would assert the model said\nnothing when in fact it said something that was not text.\n',
    )
    toolCalls: list[dict[str, Any]] | None = Field(
        None,
        description="On an **assistant** message: the tool calls the model made,\nin OpenAI's `{id, type, function: {name, arguments}}` shape.\n\nDeliberately loose here. This is the *shared* schema, so a\ntightly-typed copy would be a third definition of the same\nobject alongside the gateway's and the driver's, and the one\nplace all three must agree is the wire format, which is\nOpenAI's and not ours to restate. The two API documents\ncarry the strict shapes.\n",
    )
    toolCallId: str | None = Field(
        None,
        description='On a **tool** message: which call this is the result of.\n`content` is the result, serialized by the caller.\n',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the agent's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the agent, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the agent's
    `GET /v1/runtimes`.

    `control` is the trust root, node registry, install-wide
    topology and UI host — exactly one active, plus warm standbys.
    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives. `library` scans the operator's model
    directories and holds per-model launch profiles; there is
    exactly one, and it is deliberately not in the request path.

    **The agent is not in this list**, for the same reason engine
    runtimes are not: it supervises, it is not supervised. Its
    lifecycle belongs to the platform — a systemd unit, a container
    entrypoint — not to a topology entry. `control` *is* in the list
    precisely because the agent on its host supervises it like
    anything else, which is what stops the control root needing a
    second copy of the supervision machinery.

    """

    control = 'control'
    gateway = 'gateway'
    inference_driver = 'inference-driver'
    library = 'library'


class ComputeDeviceKind(StrEnum):
    """
    What kind of device this is.

    A named schema rather than an inline enum because an inline one
    generated a bare `Kind` class, which is too generic to sit in a
    module every component imports.

    Note `cpu` is a member, which is why the surrounding schema is
    `ComputeDevice` and not `Accelerator`: a list that includes CPUs
    is a device list. The narrower `HostAccelerator.accelerator` on
    the agent keeps its own name and its own values — it answers
    "which prebuilt engine build fits this machine", not "what can
    this host compute on".

    """

    cuda = 'cuda'
    rocm = 'rocm'
    xpu = 'xpu'
    metal = 'metal'
    cpu = 'cpu'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `llama_cpp` drives upstream `llama-server` and loads GGUF.
    `vllm` drives upstream `vllm serve` and loads safetensors. MLX
    is a third adapter later. We never ship an engine — every one of
    them is an upstream project we wrap and track.

    The two differ in far more than argv, and that is why readiness
    is per-adapter rather than one shared TCP check:
    `llama-server` answers `/health` while it loads and reports that
    it is loading, whereas vLLM binds its port *before* loading the
    model and refuses connections until the model is in memory — so
    for minutes it is indistinguishable, over the network alone,
    from a process that died. They differ in acquisition too: a
    llama.cpp build is fetched and verified by us, while vLLM is a
    Python package the operator installs themselves. See
    `EngineAcquisition.policy`.

    Lives here rather than on the agent because two components
    reference it: the agent's engines and runtimes, and a
    library `ModelProfile`, which names the engine its launch flags
    are written for.

    """

    llama_cpp = 'llama_cpp'
    vllm = 'vllm'


class ModelFormat(StrEnum):
    """
    On-disk format of a model. A dimension of the data model rather
    than an assumption (locked 2026-09-08): both are implemented at
    v0.1, and the differences are load-bearing rather than
    cosmetic.

    * `gguf` — a single file, quantized, carrying its own metadata
      and tokenizer. Large models may be **split** into
      `…-00001-of-0000N.gguf` shards, of which only the first is
      named on a launch line. A multimodal GGUF ships its vision
      projector as a separate file in the same directory, which is
      not itself a model.
    * `safetensors` — a directory: `config.json` plus one or more
      weight files plus tokenizer files. Unquantized in practice,
      so **no quant tier** — a safetensors model is sized, not
      tiered, and the quant fields exist only on the GGUF side.

    Shared because it appears on both sides of a join: a library
    entry declares what a model *is*, and
    `EngineDescriptor.modelFormats` declares what an engine can
    *load*. Nothing can serve a safetensors model until the vLLM
    adapter lands, and that answer comes from the engine's
    descriptor rather than from anything the library knows.

    """

    gguf = 'gguf'
    safetensors = 'safetensors'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the agent's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    Three of these hold more than a scalar. `path_list` is an
    ordered JSON array of directory paths on the component host —
    the library's model roots are the first and so far only user —
    and the UI renders it as an add/remove list of directory pickers
    rather than a text field, because asking someone to
    comma-separate Windows paths is asking for a bug report. Order
    is preserved and meaningful: it is the order the operator sees,
    and M3's downloader offers the first entry as the default
    destination.

    `url_list` is the same argument one type over: an ordered JSON
    array of URLs, rendered as an add/remove list of address fields.
    Added at M5 for the control root's standby endpoints, which are
    inherently plural — *"N standbys is a configuration, not a
    mechanism"* — and which have no natural single-value spelling.
    A comma-separated text field would be the same bug report
    `path_list` exists to avoid, and reusing `path_list` for
    addresses would tell every UI to open a directory picker.
    Validation is the field's business rather than the type's; what
    the type promises is a list whose entries are addresses.

    `runtime_name` holds the `name` of a supervised engine runtime,
    and UIs render it as a dropdown sourced from the agent's
    `GET /v1/runtimes`. It exists because `componentKindHint` cannot
    do this job: a runtime is deliberately not a component, so
    `/v1/components` does not list one. What is saved is the
    runtime's *name*, never its URL — the agent assigns the port
    when the operator does not pick one, so a stored URL would
    encode a number the operator never chose and does not own, and
    would be wrong the moment the runtime moved. Its first user is
    the inference-driver's `runtimeName`, which is how a driver
    follows the engine process it fronts.

    `node_name` holds the `name` of an enrolled node, rendered as a
    dropdown sourced from the control root's `GET /v1/nodes`. Same
    reasoning as `runtime_name` one level up: a node is not a
    component either, so `componentKindHint` cannot source it, and
    what is saved is the name rather than a URL because the address
    of a host is topology the control root owns.

    `model_slots` is the gateway's priority-list surface, and the
    one value here that holds objects. An ordered JSON array of
    `{"model": <alias a client asks for>, "targets": [<model id>,
    ...]}`: a request for `model` is served by the drivers serving
    `model` itself, then by the drivers serving each target in
    order, cascading on failure. Targets are **model ids, not driver
    names**, because a model id names a replica set — every driver
    currently serving it, load-balanced — and a driver name would
    name one process. That is why the value reserved since M2 as
    `driver_list` was renamed when M6 defined it: the old name said
    the wrong thing about what goes in the list. A cloud
    subscription is a target like any other, because a
    `claude_code_cli` driver already serves a model id. UIs without
    a structured renderer for it fall back to editing the JSON.

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    path_list = 'path_list'
    url = 'url'
    url_list = 'url_list'
    duration = 'duration'
    runtime_name = 'runtime_name'
    node_name = 'node_name'
    model_slots = 'model_slots'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the agent handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every agent
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the agent. The passphrase is the same one the operator set
    in the wizard. The agent bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the agent at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the agent's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class ModelRoutingInfo(BaseModel):
    """
    Namespaced extension: how this install serves the model. Present
    so the UI can render the routing table straight off the standard
    endpoint instead of needing a parallel admin call, and so an
    operator can see that a name is backed by two replicas.

    """

    drivers: list[str] | None = Field(
        None, description='Names of the inference-drivers currently serving this model.'
    )
    backends: list[BackendKind] | None = Field(
        None, description='Distinct wire protocols behind this model.'
    )
    context_length: int | None = Field(
        None,
        description='Smallest context window among the serving backends — the\nhonest number, since a request may land on any of them.\n',
    )
    tool_calling: bool | None = Field(
        None,
        description='Whether a request for this model may carry `tools`.\n\n**True only when every backend serving it can**, by the same\nreasoning as `context_length` above: a request may land on\nany of them, so the honest answer is the weakest one. A\nharness can read this and pick a model rather than discover\nthe limit as a 400 halfway through a task.\n',
    )
    tiers: list[list[str]] | None = Field(
        None,
        description="The slot's tiers in priority order, each the driver names\nin it. One tier for an unconfigured model; more when a\n`modelSlots` entry adds targets. Empty tiers are omitted.\n",
    )
    ready_backends: int | None = Field(
        None,
        description='How many of those drivers can take a request right now — a\nreachable driver whose runtime is `ready`, or that follows\nno runtime. Zero with the model still listed means every\nruntime behind it is asleep and at least one will wake on\ndemand.\n',
        ge=0,
    )
    on_demand: bool | None = Field(
        None,
        description='True when a request for this model may have to wait for a\nruntime to start — every eligible backend is `stopped` and\nat least one declared `startOnDemand`.\n',
    )


class ToolChoice(StrEnum):
    """
    How the model should use `tools`. `auto` is the default when
    tools are present, `none` forbids calling one, `required`
    forces at least one call, and an object names a specific
    function. Passed through; the gateway does not enforce it.

    """

    none = 'none'
    auto = 'auto'
    required = 'required'


class Role1(StrEnum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class FinishReason(StrEnum):
    """
    `stop` for a natural end or a matched stop sequence,
    `length` for hitting the token cap, `tool_calls` when the
    model stopped because it wants one or more tools run.

    Until 2026-09-11 this enum was `stop` and `length` only, and
    its description said so in as many words — "OpenAI's two
    values for a completion **without** tool calls". That
    sentence was the single occurrence of the string "tool"
    anywhere in this contract or the driver's, and it was an
    accurate description of a control plane no agent harness
    could use.

    """

    stop = 'stop'
    length = 'length'
    tool_calls = 'tool_calls'


class Role2(StrEnum):
    assistant = 'assistant'


class FinishReason1(Enum):
    """
    Null until the terminal chunk.
    """

    stop = 'stop'
    length = 'length'
    tool_calls = 'tool_calls'
    NoneType_None = None


class FunctionDefinition(BaseModel):
    name: str = Field(..., description='The name the model calls, e.g. `read_file`.')
    description: str | None = Field(
        None,
        description='What the tool does. Load bearing rather than decorative —\nit is the only thing the model has to decide *whether* to\ncall this tool.\n',
    )
    parameters: dict[str, Any] | None = Field(
        None,
        description='A JSON Schema object describing the arguments. Passed\nthrough verbatim: we do not validate it, rewrite it, or\ntranslate dialects. A backend that rejects a construct\nrejects it in its own words, which is more useful than a\nguess of ours made one hop earlier.\n',
    )
    strict: bool | None = Field(
        None,
        description='Ask the backend to constrain generation to `parameters`.\nPassed through; backends that do not support it ignore it.\n',
    )


class Function(BaseModel):
    name: str


class NamedToolChoice(BaseModel):
    """
    Force one specific function.
    """

    type: Literal['function']
    function: Function


class FunctionCall(BaseModel):
    name: str
    arguments: str = Field(
        ...,
        description="The arguments as a **JSON string**, not an object. That is\nOpenAI's shape and it is deliberate on their part: a model\ncan emit invalid JSON, and a string preserves what it\nactually said instead of failing the whole response. The\ncaller parses it and handles the failure. We do not parse\nit, so we cannot lose it.\n",
    )


class Function1(BaseModel):
    name: str | None = None
    arguments: str | None = Field(
        None, description='A fragment of the arguments string, to be concatenated.'
    )


class ToolCallDelta(BaseModel):
    """
    A fragment of a `ToolCall` in a streaming response. Accumulate
    by `index`.

    """

    index: int = Field(
        ...,
        description='Which call in the assistant turn this fragment belongs to.\nPresent on every fragment, because a model can interleave\nfragments of two calls.\n',
    )
    id: str | None = None
    type: Literal['function'] = 'function'
    function: Function1 | None = None


class Type(StrEnum):
    text = 'text'
    json_object = 'json_object'
    json_schema = 'json_schema'


class ResponseJsonSchema(BaseModel):
    name: str
    description: str | None = None
    schema_: dict[str, Any] = Field(
        ...,
        alias='schema',
        description='A JSON Schema object. Passed through verbatim.',
    )
    strict: bool | None = None


class CompletionUsage(BaseModel):
    """
    Token accounting in OpenAI's field names. Fields may be absent
    when the backend did not report them on that request.

    This used to say the CLI subprocess backends "generally do not",
    which is wrong and was believed downstream: both of them parse a
    usage block out of their CLI's output — Claude's envelope,
    Codex's `turn.completed` — and omit it only when the CLI emitted
    none.

    """

    prompt_tokens: int | None = Field(None, ge=0)
    completion_tokens: int | None = Field(None, ge=0)
    total_tokens: int | None = Field(None, ge=0)


class CompletionRoutingInfo(BaseModel):
    """
    Namespaced extension recording how this particular request was
    served. Not part of OpenAI's schema, and ignored by clients that
    do not know it.

    It exists because the failure mode of a routing layer is being
    opaque: when one of several backends is slow or a cascade fired,
    an operator needs to see which one answered without going to the
    logs. `attempts` above 1 is the visible evidence that failover
    did its job.

    """

    driver: str | None = Field(
        None, description='Name of the inference-driver that served this request.'
    )
    runtime: str | None = Field(
        None,
        description='Name of the engine runtime behind that driver, when it is a\nlocal engine. Absent for hosted and CLI backends, which have\nno runtime of ours.\n',
    )
    backend: BackendKind | None = None
    latency_ms: int | None = Field(
        None, description='Gateway-side wall-clock time, including any failed attempts.'
    )
    attempts: int | None = Field(
        None,
        description='How many backends were tried. Greater than 1 means the\npriority-list cascade fired and an earlier backend failed.\n',
        ge=1,
    )
    tier: int | None = Field(
        None,
        description='Which tier of the slot answered, 1-based. Greater than 1\nmeans every backend in an earlier tier was ineligible or\nfailed — a cloud target answering for a local model, say.\n',
        ge=1,
    )
    swapped_in: bool | None = Field(
        None,
        description='True when the gateway had to start a `startOnDemand`\nruntime to serve this request. The visible cost of idle\nunload, next to the request that paid it.\n',
    )
    waited_ms: int | None = Field(
        None,
        description='How long the request waited for a runtime to reach `ready`\nbefore being sent. Zero when nothing had to be woken.\n',
        ge=0,
    )
    context_length: int | None = Field(
        None,
        description='The context window of the backend that actually answered, as\nthat backend resolved it. **Null** when it does not expose\none — a hosted provider, a CLI subscription, or a local\nengine that was not reachable to ask. Null and not absent:\nthis envelope serializes its unset fields, as `runtime` has\nsince M0.\n\nPer-request, and therefore not the same number as\n`x_eugene_plexus.context_length` on `GET /v1/models`: that\none is the smallest across every backend serving the name,\nbecause a request may land on any of them. This one is the\nwindow that applied to *this* request, which is what makes a\ntruncated answer explicable after the fact.\n',
        ge=1,
    )
    prompt_truncated: bool | None = Field(
        None,
        description="**The backend silently dropped input.** True when the prompt\nwe sent was far larger than the token count the backend\nreported consuming — the signature of a server that fits an\nover-long prompt into the window by discarding the middle of\nthe conversation and answering anyway, with a 200 and no\nflag of its own.\n\nThis is the failure that makes a coding harness loop: it\nsends file contents, the model never receives them, and the\nconfident answer that comes back is about code nobody read.\nMeasured on this project's own hardware: 66,389 characters\nacross six messages came back as `prompt_tokens: 86`, HTTP\n200, nothing anywhere saying so.\n\nDetected, not predicted. It is computed from\n`usage.prompt_tokens` **after** the answer, by a ratio\nchosen to be far below any real tokenizer's — so it cannot\nfire on a merely token-dense prompt, and it needs no\ntokenizer of ours.\n\n**Three states, and the difference matters.** `null` means\nnot evaluated — the backend reported no usage, or the prompt\nwas too small for the test to mean anything — and must not\nbe read as reassurance. `false` means it was checked and the\ninput arrived. `true` means it did not. Null and not absent:\nthis envelope serializes its unset fields, as `runtime` has\nsince M0.\n\n**Why a flag and not an error.** The answer has already been\ngenerated, and on a streamed request it has already been\ndelivered — M10's rule is that a stream cannot be unsent.\nFailing one path and flagging the other would make the same\ncondition report two different ways, so both flag. A backend\nthat refuses instead of truncating needs none of this: its\nrefusal is exact and is passed straight through as a 400.\n",
    )


class RoutingBackendView(BaseModel):
    driver: str
    url: AnyUrl | None = None
    eligible: bool = Field(
        ..., description='Whether a request could be sent here right now.'
    )
    ineligible_reason: str | None = Field(
        None,
        description="Why not, when `eligible` is false — the runtime's status\n(`stopped`, `loading`, `crashed`), or that the driver was\nunreachable.\n",
    )
    in_flight: int | None = Field(
        None, description='Requests this gateway currently has outstanding to it.', ge=0
    )
    parallel_slots: int | None = Field(
        None,
        description="The runtime's capacity, when it reported one; 1 otherwise.",
        ge=1,
    )
    runtime: str | None = Field(
        None, description='The engine runtime this driver follows, when it follows one.'
    )
    runtime_status: str | None = Field(
        None,
        description="The agent's `RuntimeStatus` for that runtime, as a string —\nthe agent owns the enum.\n",
    )
    node: str | None = Field(
        None, description='The node the runtime runs on, when the agent reports one.'
    )
    stop_reason: str | None = Field(
        None,
        description="The agent's `Runtime.stopReason`, when the runtime is stopped.",
    )
    idle_unload_seconds: int | None = Field(
        None, description="The runtime's declared idle timeout, when it has one."
    )
    start_on_demand: bool | None = None
    idle_seconds: int | None = Field(
        None,
        description='Seconds since the gateway last sent this backend a request.\nAbsent when it never has.\n',
        ge=0,
    )


class Error(BaseModel):
    message: str = Field(
        ...,
        description='Human-readable failure. Names the model and, on a\ncascade, that every backend was tried — the operator\nreading it is usually the person who configured the\nthing.\n',
    )
    type: str = Field(
        ..., description='OpenAI-style class, e.g. `invalid_request_error`.'
    )
    param: str | None = None
    code: str | None = None


class OpenAIErrorResponse(BaseModel):
    """
    Error envelope for the two OpenAI-compatible operations. The
    rest of the gateway returns RFC 7807 `problem+json`; these two
    cannot, because OpenAI SDKs parse this shape to build their
    exceptions and would report a problem+json body as an unhelpful
    generic failure. One surface, one foreign convention, honoured
    exactly.

    """

    error: Error


class Percentiles(BaseModel):
    """
    A latency distribution, in milliseconds. Percentiles rather than
    a mean because generation latency is long-tailed, and a mean
    hides exactly the requests an operator is asking about.

    """

    p50: int = Field(..., ge=0)
    p90: int = Field(..., ge=0)
    p99: int | None = Field(None, ge=0)
    max: int = Field(..., ge=0)


class Throughput(BaseModel):
    """
    Completion tokens per second, computed from the **serving
    attempt's** elapsed time — not the request total, which
    includes failed attempts.

    `samples` is how many requests in the group actually reported
    token usage, and can be lower than the group's `requests`. A
    group where nothing reported usage is not given a zeroed
    `Throughput`: the field is null instead, so "unmeasured" and
    "zero" stay distinguishable.

    """

    p50: float
    p90: float | None = None
    samples: int = Field(..., ge=1)


class MetricsGroup(BaseModel):
    """
    One dimension tuple's numbers over the window, or over one hour
    of it when `bucket=hour`.

    """

    bucketStart: AwareDatetime | None = Field(
        None, description='Present only when `bucket=hour`.'
    )
    model: str | None = Field(
        None,
        description='The model id the client **asked for**. After a cascade this\nis not what answered — `driver` and `runtime` say that —\nand grouping by the requested id is what makes "this model\nis slow" answerable at all.\n',
    )
    driver: str | None = None
    runtime: str | None = Field(
        None,
        description='The engine runtime behind the driver, by name so replicas\nare distinguished. Null for hosted and CLI backends, which\nhave no runtime of ours.\n',
    )
    node: str | None = Field(
        None, description="Which host's agent supervises it. Null before enrollment."
    )
    backend: BackendKind | None = None
    requests: int = Field(..., ge=0)
    errors: int = Field(
        ..., description='Requests that ended with no backend having served them.', ge=0
    )
    cascaded: int = Field(
        ...,
        description='Requests with `attempts > 1`. A cascade that silently\nalways works hides a broken primary, which is why this is\ncounted rather than only logged.\n',
        ge=0,
    )
    swappedIn: int = Field(
        ...,
        description="Requests that had to wake a `startOnDemand` runtime. The\nmeasured cost of M6's idle unload, which shipped with no\nway to see what it costs.\n",
        ge=0,
    )
    latencyMs: Percentiles
    tokensPerSecond: Throughput | None = Field(
        None, description='Null when no request in this group reported token usage.'
    )
    waitedMs: Percentiles | None = Field(
        None,
        description='Wake latency, over the `swappedIn` requests only. Null when\nnone of them woke anything.\n',
    )
    routingMs: Percentiles | None = Field(
        None,
        description='How long deciding where to send the request took. Null for\ngroups recorded before this was measured.\n',
    )
    overheadMs: Percentiles | None = Field(
        None,
        description="The control plane's own cost: the serving attempt's\ngateway-side time minus the driver's measurement of its\nbackend call. Null when no request in the group had a\nbackend that reported its own latency.\n",
    )
    tierCounts: dict[str, int] | None = Field(
        None,
        description='Requests served, keyed by the 1-based tier that answered. A\nslot whose tier 2 answers everything has a primary that is\nnot working, and this is where that becomes visible.\n',
    )


class MetricsSummary(BaseModel):
    windowStart: AwareDatetime
    windowEnd: AwareDatetime
    gatewayStartedAt: AwareDatetime = Field(
        ...,
        description='When this gateway process started. Present so a history\nthat begins mid-window reads as partial rather than as an\ninstall that served nothing — the gateway is respawned on\noperator login, so a fresh start time is routine.\n',
    )
    rowsDropped: int = Field(
        ...,
        description='Measurements discarded since startup because the write\nqueue was full. Non-zero means these numbers are a sample\nrather than a census, and the endpoint says so instead of\nquietly under-reporting. Recording degrades before\ninference does.\n',
        ge=0,
    )
    truncated: bool | None = Field(
        None,
        description='True when the window reaches past `metricsRetentionDays`,\nso raw rows for its early part no longer exist and the\nnumbers describe less than the window asked for. Hourly\nrollups do cover that period on disk; nothing serves them\nyet.\n',
    )
    groups: list[MetricsGroup]


class MetricAttempt(BaseModel):
    """
    One backend touched by one request, in the order tried.
    """

    driver: str
    runtime: str | None = None
    node: str | None = None
    backend: BackendKind | None = None
    elapsedMs: int = Field(
        ...,
        description='This attempt alone, not the request. Gateway-side, so it\nincludes the local hop to the driver.\n',
        ge=0,
    )
    backendMs: int | None = Field(
        None,
        description='The **driver\'s** own measurement of its backend call\n(`GenerateResponse.latencyMs`), when it reported one.\n\n`elapsedMs - backendMs` is therefore the cost of the\ngateway-to-driver hop plus the driver\'s own work: the\ncontrol plane\'s overhead on this request. This document\nasserted from M0 to M8 that the extra local hop was\n"sub-millisecond against a multi-second generation" and "not\na cost worth optimising away" - an architectural\njustification nobody had measured. Both numbers were already\nbeing produced; subtracting them made the claim checkable,\nand **the first time it ran it came back 114-120 ms**. See\nthis document\'s overview.\n',
        ge=0,
    )
    served: bool
    error: str | None = Field(
        None,
        description="The exception **class name** only, never its message.\nDriver error text can carry a provider's response body, and\na metrics table is the kind of thing that gets pasted into\nan issue — this must not become an accidental credential\nstore.\n",
    )


class Outcome(StrEnum):
    served = 'served'
    error = 'error'


class MetricCandidate(BaseModel):
    """
    One backend the balancer considered for a request, and what it
    saw when it decided.

    Deliberately the **input** to the decision rather than a score.
    There is no score: `least_busy` is a sort by in-flight requests
    per slot of capacity, and inventing a number to display would be
    inventing the smarter balancer that was explicitly deferred.
    What this answers is the question an operator actually asks —
    why did this request go there and not to the other one.

    Recorded only when there was a decision to make: more than one
    candidate, or at least one rejected. A single eligible backend is
    not an audit trail.

    """

    driver: str
    tier: int = Field(..., ge=1)
    eligible: bool = Field(
        ...,
        description='Whether this backend could take the request at all. A driver\nfollowing a runtime is eligible only while that runtime is\n`ready`; one following nothing of ours is eligible whenever\nit is reachable.\n',
    )
    reason: str | None = Field(
        None, description='Why not, when `eligible` is false. Null when it was.'
    )
    inFlight: int | None = Field(
        None,
        description='Requests already outstanding to this backend when the choice\nwas made. The load signal `least_busy` sorts on.\n',
        ge=0,
    )
    slots: int | None = Field(
        None,
        description="The runtime's `parallelSlots`, its concurrent capacity. The\nbalancer compares `inFlight / slots`, not `inFlight`, so a\nfour-slot replica holding two requests is less loaded than a\none-slot replica holding one.\n",
        ge=1,
    )


class DriverHealth(BaseModel):
    """
    What the gateway sees from one inference-driver's `/v1/info`,
    plus the gateway-side reachability status and the
    operator-supplied `name`.

    """

    name: str = Field(
        ...,
        description="Operator-supplied driver name from the gateway's\n`drivers` config. UI uses this as the tab/column label.\n",
    )
    reachable: bool
    url: AnyUrl | None = Field(None, description='How the gateway reaches this driver.')
    backend: BackendKind | None = None
    modelId: str | None = None
    runtime: str | None = Field(
        None,
        description='The supervised engine runtime this driver follows, straight\noff its `/v1/info`. Absent for a backend that is not a\nruntime this install supervises.\n\nCarried up because it answers the one question this panel\ncould not previously answer: a driver that is reachable but\nserves nothing, next to a runtime that is `ready` and\nrouted to by nobody, is the visible shape of a\nmis-wired install.\n',
    )
    version: str | None = None
    error: str | None = Field(None, description='Populated when `reachable: false`.')


class ComputeDevice(BaseModel):
    """
    One compute device on one host, as that host's agent detected it.

    Shared because it appears on both sides of a join: an agent
    reports its own devices on `GET /v1/node`, and the control root
    aggregates them into `Node.devices` — the cross-host
    inventory M3 deferred with the note that *"building a real
    inventory is topology work"*. Two copies of this shape would be
    two definitions of one fact, and the copy would be the one that
    went stale.

    Deliberately **not** the same thing as the agent's
    `HostAccelerator`, which answers a narrower question — "which
    prebuilt engine build should we fetch for this machine" — and
    describes a host in the singular. This is a device *list*,
    because a host with two cards is the case that makes replicas of
    one model possible.

    """

    kind: ComputeDeviceKind
    name: str | None = Field(
        None,
        description='Device name as the vendor reports it, e.g. `NVIDIA GeForce RTX 5090`.',
    )
    index: int | None = Field(
        None,
        description="Device ordinal on its own host — what `CUDA_VISIBLE_DEVICES`\nor `HIP_VISIBLE_DEVICES` in a runtime's `env` selects to pin\nthat runtime to one card.\n",
        ge=0,
    )
    memoryTotalBytes: int | None = None
    memoryFreeBytes: int | None = Field(
        None,
        description='Free decides whether a model fits, not total — M3 measured\n2.9 GiB of a 32 GiB card already held on an idle desktop.\nBoth are reported so the difference is visible rather than\nsurprising.\n',
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the agent's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class Model(BaseModel):
    """
    One routable model, in OpenAI's shape plus one namespaced
    extension. Unknown fields are ignored by OpenAI clients, which
    is what makes it safe to answer "which of my backends is behind
    this name" without breaking compatibility.

    """

    id: str = Field(
        ...,
        description="What the client puts in `ChatCompletionRequest.model`. For a\nlocal runtime this is its `modelAlias`, which defaults to\nthe model's own filename — so the name a user sees is the\nname of the file they downloaded.\n",
    )
    object: Literal['model']
    created: int | None = Field(
        None, description='Unix timestamp. Model file mtime for local models.'
    )
    owned_by: str | None = Field(
        None,
        description='OpenAI sends an organisation here. We send the provider —\n`local`, or the cloud provider key for a subscription\nbackend.\n',
    )
    x_eugene_plexus: ModelRoutingInfo | None = None


class Delta(BaseModel):
    """
    Incremental payload. The first chunk carries `role`;
    subsequent chunks carry `content` fragments, `tool_calls`
    fragments, or neither on the terminal chunk.

    """

    role: Role2 | None = None
    content: str | None = None
    tool_calls: list[ToolCallDelta] | None = Field(
        None,
        description='Tool-call fragments. Each carries an `index` and the\ncaller accumulates by it: `id` and `function.name`\narrive once, `function.arguments` arrives as a string\nsplit across any number of frames. A single frame is\n**not** parseable JSON and was never meant to be.\n',
    )


class ChatCompletionChunkChoice(BaseModel):
    index: int
    delta: Delta = Field(
        ...,
        description='Incremental payload. The first chunk carries `role`;\nsubsequent chunks carry `content` fragments, `tool_calls`\nfragments, or neither on the terminal chunk.\n',
    )
    finish_reason: FinishReason1 | None = Field(
        None, description='Null until the terminal chunk.'
    )


class Tool(BaseModel):
    """
    One tool offered to the model. OpenAI has only ever defined
    `function`, and the wrapper exists so other kinds can be added
    without reshaping the field.

    """

    type: Literal['function']
    function: FunctionDefinition


class ToolCall(BaseModel):
    """
    One tool call the model chose to make.
    """

    id: str = Field(
        ...,
        description='Correlation id. The caller echoes it as `tool_call_id` on\nthe message carrying the result.\n',
    )
    type: Literal['function']
    function: FunctionCall


class ResponseFormat(BaseModel):
    """
    Constrain the shape of the reply. Passed through to the backend;
    the gateway does not enforce or post-validate it.

    """

    type: Type
    json_schema: ResponseJsonSchema | None = Field(
        None, description='Required when `type` is `json_schema`.'
    )


class RoutingTierView(BaseModel):
    target: str = Field(
        ..., description='The model id this tier is the replica set of.'
    )
    backends: list[RoutingBackendView]


class MetricRequest(BaseModel):
    startedAt: AwareDatetime
    requestedModel: str
    servedModel: str | None = Field(
        None,
        description='What actually answered. Differs from the requested id after\na cascade.\n',
    )
    attempts: int = Field(..., ge=1)
    tier: int | None = Field(None, ge=1)
    totalMs: int = Field(
        ...,
        description='Gateway-side wall clock for the whole request, including\nfailed attempts and excluding the wake — the same figure\n`x_eugene_plexus.latency_ms` reports. Per-backend\nthroughput comes from `tries[].elapsedMs`, never from here.\n',
        ge=0,
    )
    routingMs: int | None = Field(
        None,
        description="Time spent deciding where to send this request - resolving\nthe model to a slot, picking a backend, and any\nrouting-table refresh that happened on the way - measured\n**before** `totalMs` starts and excluding the wake, which is\n`waitedMs`.\n\nPreviously invisible, and not always small: a refresh does\nHTTP to the agent and to every driver's `/v1/info`, inside\nthe request that triggered it.\n",
        ge=0,
    )
    refreshed: bool | None = Field(
        None,
        description='Whether a routing-table refresh ran inside this request.\nThe expensive and surprising case, so it is a flag rather\nthan something to infer from `routingMs`.\n',
    )
    strategy: str | None = Field(
        None,
        description='The `loadBalancing` value in effect when this request was\nrouted. Recorded per request because the config can change\nbetween them, and `least_busy` and `round_robin` explain\ndifferent orderings.\n',
    )
    candidates: list[MetricCandidate] | None = Field(
        None,
        description='What the balancer considered. Present only when there was a\ndecision to make - more than one candidate, or at least one\nrejected.\n',
    )
    waitedMs: int | None = Field(None, ge=0)
    swappedIn: bool | None = None
    streamed: bool | None = Field(
        None,
        description='Whether the client asked for SSE. Recorded because streamed\nrequests were invisible to the response envelope, and a\nstore that could not tell them apart would hide the very\ngap it was built to close.\n',
    )
    promptTokens: int | None = None
    completionTokens: int | None = None
    outcome: Outcome
    tries: list[MetricAttempt] = Field(..., min_length=1)


class MetricRequestPage(BaseModel):
    requests: list[MetricRequest]
    nextCursor: str | None = Field(None, description='Absent or null on the last page.')


class DriversInfo(BaseModel):
    drivers: list[DriverHealth] = Field(
        ...,
        description="Per-driver health snapshot, ordered as the gateway's\n`drivers` config declared them.\n",
    )


class ModelList(BaseModel):
    object: Literal['list']
    data: list[Model]


class ChatCompletionMessage(BaseModel):
    """
    OpenAI-shaped chat message. Intentionally *not* the shared
    `Message` schema: this one is on a wire contract we do not own,
    so it carries exactly OpenAI's fields and nothing of ours.
    Leaking a house field like `timestamp` into a payload an OpenAI
    SDK parses is how "compatible" quietly stops being true.

    """

    role: Role1
    content: str | None = Field(
        None,
        description='The message text. **Nullable, and that is not laxity:** an\nassistant message that only calls a tool has no text, and\nOpenAI sends `content: null` alongside `tool_calls` for it.\nA schema that required a string here would reject the\nsingle most common assistant turn in an agent loop.\n',
    )
    name: str | None = Field(None, description='Optional participant name, per OpenAI.')
    tool_calls: list[ToolCall] | None = Field(
        None,
        description='Set on an **assistant** message, naming the tools the model\nchose to call. The caller executes them and replies with one\n`tool` message per call, each carrying the matching\n`tool_call_id`.\n',
    )
    tool_call_id: str | None = Field(
        None,
        description='Required on a **tool** message: which call in the preceding\nassistant turn this is the result of. `content` is the\nresult, as a string — the caller serializes it.\n',
    )


class ChatCompletionChoice(BaseModel):
    index: int
    message: ChatCompletionMessage
    finish_reason: FinishReason = Field(
        ...,
        description='`stop` for a natural end or a matched stop sequence,\n`length` for hitting the token cap, `tool_calls` when the\nmodel stopped because it wants one or more tools run.\n\nUntil 2026-09-11 this enum was `stop` and `length` only, and\nits description said so in as many words — "OpenAI\'s two\nvalues for a completion **without** tool calls". That\nsentence was the single occurrence of the string "tool"\nanywhere in this contract or the driver\'s, and it was an\naccurate description of a control plane no agent harness\ncould use.\n',
    )


class ChatCompletionChunk(BaseModel):
    """
    One SSE frame of a streaming completion.
    """

    id: str
    object: Literal['chat.completion.chunk']
    created: int
    model: str
    choices: list[ChatCompletionChunkChoice]
    usage: CompletionUsage | None = None
    x_eugene_plexus: CompletionRoutingInfo | None = Field(
        None,
        description='Set on the **final frame only**, alongside `usage` — the\nsame place OpenAI puts its own end-of-stream extras.\nAbsent on every earlier frame, because the values are not\nknown until the completion is done.\n\nAdded at M8. Until then a streaming client could see no\nrouting information at all: the non-streaming response\ncarried this and the stream did not, so exactly the clients\nthat stream — the UI playground among them — were the ones\nthat could not tell which backend answered. Retained\nmetrics do not depend on this (they are recorded at the\nrouting hooks, which fire on both paths); this closes the\nmatching gap in what a caller can see.\n',
    )


class RoutingSlotView(BaseModel):
    model: str = Field(..., description='What a client asks for.')
    configured: bool | None = Field(
        None,
        description='True when a `modelSlots` entry exists for this model; false\nfor the implicit one-tier slot every served model id gets.\n',
    )
    tiers: list[RoutingTierView]


class ChatCompletionRequest(BaseModel):
    model: str = Field(
        ...,
        description='A model id from `GET /v1/models`. The gateway resolves it to\na backend; the client does not choose a backend.\n',
    )
    messages: list[ChatCompletionMessage] = Field(..., min_length=1)
    max_tokens: int | None = Field(
        None,
        description="Maximum output tokens. Filled from the model's settings\nprofile when omitted, then always sent downstream\nexplicitly.\n",
        ge=1,
    )
    temperature: float | None = Field(None, ge=0.0, le=2.0)
    top_p: float | None = Field(None, ge=0.0, le=1.0)
    stop: list[str] | None = Field(None, description='Stop sequences.', max_length=4)
    seed: int | None = Field(
        None,
        description='Passed through to backends that support deterministic\nsampling; dropped with a warning where they do not.\n',
    )
    stream: bool | None = Field(
        False,
        description='When true the response is an SSE stream of\n`ChatCompletionChunk` objects terminated by `data: [DONE]`.\n',
    )
    user: str | None = Field(
        None, description='Opaque client-supplied identifier, echoed into logs only.'
    )
    tools: list[Tool] | None = Field(
        None,
        description='Tools the model may call. Passed through to the backend\nunchanged; the gateway never invents, filters or reorders\nthem.\n\n**The gateway does not execute tools.** It carries the\ndefinitions down and the model\'s chosen calls back up, and\nthe caller runs them and sends the results as `tool` role\nmessages. That is OpenAI\'s contract and it is the one an\nagent harness implements.\n\nA backend that cannot carry tools is not silently stripped:\nthe request fails with a 400 naming the backend, because a\nharness that receives a plain answer where it expected a\ntool call has no way to tell "the model chose not to" from\n"nobody ever offered it the tools" — and the second is a\nbug that looks exactly like the first. `GET /v1/models`\nreports which models can.\n',
    )
    tool_choice: ToolChoice | NamedToolChoice | None = Field(
        None,
        description='How the model should use `tools`. `auto` is the default when\ntools are present, `none` forbids calling one, `required`\nforces at least one call, and an object names a specific\nfunction. Passed through; the gateway does not enforce it.\n',
    )
    response_format: ResponseFormat | None = None


class ChatCompletionResponse(BaseModel):
    id: str = Field(
        ..., description='Completion id, `chatcmpl-` prefixed as clients expect.'
    )
    object: Literal['chat.completion']
    created: int
    model: str = Field(
        ...,
        description='The model that actually served the request. Equal to the\nrequested id in the normal case; after a cascade it names\nwhat answered, which may differ.\n',
    )
    choices: list[ChatCompletionChoice]
    usage: CompletionUsage | None = Field(
        None, description='Present on the final chunk only.'
    )
    x_eugene_plexus: CompletionRoutingInfo | None = None


class RoutingTableView(BaseModel):
    """
    The gateway's resolved routing table, as of the last refresh.
    The same snapshot requests are routed from, opened up so an
    operator can see why a request went where it did.

    """

    refreshed_at: AwareDatetime
    load_balancing: str | None = Field(
        None, description='The strategy in effect — the `loadBalancing` config value.'
    )
    slots: list[RoutingSlotView]
    unreachable_drivers: list[str] | None = Field(
        None, description='Drivers in the topology that did not answer `/v1/info`.'
    )
