# generated by datamodel-codegen:
#   filename:  gateway.yaml

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class DriverProbeRequest(BaseModel):
    """
    Request body for `POST /v1/admin/drivers/probe`. Tests a single
    backend URL without persisting it. A driver slot may hold
    several backends (`DriverEntry.backends`, topology entry names);
    the UI resolves each to a URL and probes them separately so an
    operator can verify every fallback before saving.

    """

    url: AnyUrl = Field(..., description='The single backend base URL to test-connect.')
    name: str | None = Field(
        None,
        description='Optional slot label, echoed into diagnostics. Not required\nto probe; the operator may be testing a URL before naming\nthe slot.\n',
    )


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str = Field(
        ...,
        description='Message text. Text-only for now; multimodal extensions deferred.',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the watchdog's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the watchdog, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the watchdog's
    `GET /v1/runtimes`.

    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives. `library` scans the operator's model
    directories and holds per-model launch profiles; there is
    exactly one, and it is deliberately not in the request path.

    """

    gateway = 'gateway'
    inference_driver = 'inference-driver'
    library = 'library'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `llama_cpp` drives upstream `llama-server`. vLLM is a second
    adapter later, and MLX after that. We never ship an engine — all
    three are upstream projects we wrap and track.

    Lives here rather than on the watchdog because two components
    reference it: the watchdog's engines and runtimes, and a
    library `ModelProfile`, which names the engine its launch flags
    are written for.

    """

    llama_cpp = 'llama_cpp'


class ModelFormat(StrEnum):
    """
    On-disk format of a model. A dimension of the data model rather
    than an assumption (locked 2026-09-08): both are implemented at
    v0.1, and the differences are load-bearing rather than
    cosmetic.

    * `gguf` — a single file, quantized, carrying its own metadata
      and tokenizer. Large models may be **split** into
      `…-00001-of-0000N.gguf` shards, of which only the first is
      named on a launch line. A multimodal GGUF ships its vision
      projector as a separate file in the same directory, which is
      not itself a model.
    * `safetensors` — a directory: `config.json` plus one or more
      weight files plus tokenizer files. Unquantized in practice,
      so **no quant tier** — a safetensors model is sized, not
      tiered, and the quant fields exist only on the GGUF side.

    Shared because it appears on both sides of a join: a library
    entry declares what a model *is*, and
    `EngineDescriptor.modelFormats` declares what an engine can
    *load*. Nothing can serve a safetensors model until the vLLM
    adapter lands, and that answer comes from the engine's
    descriptor rather than from anything the library knows.

    """

    gguf = 'gguf'
    safetensors = 'safetensors'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the watchdog's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    Two of these hold more than a scalar. `path_list` is an ordered
    JSON array of directory paths on the component host — the
    library's model roots are the first and so far only user — and
    the UI renders it as an add/remove list of directory pickers
    rather than a text field, because asking someone to
    comma-separate Windows paths is asking for a bug report. Order
    is preserved and meaningful: it is the order the operator sees,
    and M3's downloader offers the first entry as the default
    destination. `driver_list` stays reserved for M5's ordered
    model→driver priority lists.

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    path_list = 'path_list'
    url = 'url'
    duration = 'duration'
    driver_list = 'driver_list'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the watchdog handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every watchdog
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the watchdog. The passphrase is the same one the operator set
    in the wizard. The watchdog bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the watchdog at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the watchdog's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class ModelRoutingInfo(BaseModel):
    """
    Namespaced extension: how this install serves the model. Present
    so the UI can render the routing table straight off the standard
    endpoint instead of needing a parallel admin call, and so an
    operator can see that a name is backed by two replicas.

    """

    drivers: list[str] | None = Field(
        None, description='Names of the inference-drivers currently serving this model.'
    )
    backends: list[BackendKind] | None = Field(
        None, description='Distinct wire protocols behind this model.'
    )
    context_length: int | None = Field(
        None,
        description='Smallest context window among the serving backends — the\nhonest number, since a request may land on any of them.\n',
    )


class Role1(StrEnum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'


class ChatCompletionMessage(BaseModel):
    """
    OpenAI-shaped chat message. Intentionally *not* the shared
    `Message` schema: this one is on a wire contract we do not own,
    so it carries exactly OpenAI's fields and nothing of ours.
    Leaking a house field like `timestamp` into a payload an OpenAI
    SDK parses is how "compatible" quietly stops being true.

    """

    role: Role1
    content: str
    name: str | None = Field(None, description='Optional participant name, per OpenAI.')


class FinishReason(StrEnum):
    """
    `stop` for a natural end or a matched stop sequence,
    `length` for hitting the token cap — OpenAI's two values for
    a completion without tool calls.

    """

    stop = 'stop'
    length = 'length'


class ChatCompletionChoice(BaseModel):
    index: int
    message: ChatCompletionMessage
    finish_reason: FinishReason = Field(
        ...,
        description="`stop` for a natural end or a matched stop sequence,\n`length` for hitting the token cap — OpenAI's two values for\na completion without tool calls.\n",
    )


class Role2(StrEnum):
    assistant = 'assistant'


class Delta(BaseModel):
    """
    Incremental payload. The first chunk carries `role`;
    subsequent chunks carry `content` fragments.

    """

    role: Role2 | None = None
    content: str | None = None


class FinishReason1(Enum):
    """
    Null until the terminal chunk.
    """

    stop = 'stop'
    length = 'length'
    NoneType_None = None


class ChatCompletionChunkChoice(BaseModel):
    index: int
    delta: Delta = Field(
        ...,
        description='Incremental payload. The first chunk carries `role`;\nsubsequent chunks carry `content` fragments.\n',
    )
    finish_reason: FinishReason1 | None = Field(
        None, description='Null until the terminal chunk.'
    )


class CompletionUsage(BaseModel):
    """
    Token accounting in OpenAI's field names. Fields may be absent
    when the backend does not report them — the CLI subprocess
    backends generally do not.

    """

    prompt_tokens: int | None = Field(None, ge=0)
    completion_tokens: int | None = Field(None, ge=0)
    total_tokens: int | None = Field(None, ge=0)


class CompletionRoutingInfo(BaseModel):
    """
    Namespaced extension recording how this particular request was
    served. Not part of OpenAI's schema, and ignored by clients that
    do not know it.

    It exists because the failure mode of a routing layer is being
    opaque: when one of several backends is slow or a cascade fired,
    an operator needs to see which one answered without going to the
    logs. `attempts` above 1 is the visible evidence that failover
    did its job.

    """

    driver: str | None = Field(
        None, description='Name of the inference-driver that served this request.'
    )
    runtime: str | None = Field(
        None,
        description='Name of the engine runtime behind that driver, when it is a\nlocal engine. Absent for hosted and CLI backends, which have\nno runtime of ours.\n',
    )
    backend: BackendKind | None = None
    latency_ms: int | None = Field(
        None, description='Gateway-side wall-clock time, including any failed attempts.'
    )
    attempts: int | None = Field(
        None,
        description='How many backends were tried. Greater than 1 means the\npriority-list cascade fired and an earlier backend failed.\n',
        ge=1,
    )


class Error(BaseModel):
    message: str = Field(
        ...,
        description='Human-readable failure. Names the model and, on a\ncascade, that every backend was tried — the operator\nreading it is usually the person who configured the\nthing.\n',
    )
    type: str = Field(
        ..., description='OpenAI-style class, e.g. `invalid_request_error`.'
    )
    param: str | None = None
    code: str | None = None


class OpenAIErrorResponse(BaseModel):
    """
    Error envelope for the two OpenAI-compatible operations. The
    rest of the gateway returns RFC 7807 `problem+json`; these two
    cannot, because OpenAI SDKs parse this shape to build their
    exceptions and would report a problem+json body as an unhelpful
    generic failure. One surface, one foreign convention, honoured
    exactly.

    """

    error: Error


class DriverHealth(BaseModel):
    """
    What the gateway sees from one inference-driver's `/v1/info`,
    plus the gateway-side reachability status and the
    operator-supplied `name`.

    """

    name: str = Field(
        ...,
        description="Operator-supplied driver name from the gateway's\n`drivers` config. UI uses this as the tab/column label.\n",
    )
    reachable: bool
    url: AnyUrl | None = Field(None, description='How the gateway reaches this driver.')
    backend: BackendKind | None = None
    modelId: str | None = None
    version: str | None = None
    error: str | None = Field(None, description='Populated when `reachable: false`.')


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the watchdog's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class Model(BaseModel):
    """
    One routable model, in OpenAI's shape plus one namespaced
    extension. Unknown fields are ignored by OpenAI clients, which
    is what makes it safe to answer "which of my backends is behind
    this name" without breaking compatibility.

    """

    id: str = Field(
        ...,
        description="What the client puts in `ChatCompletionRequest.model`. For a\nlocal runtime this is its `modelAlias`, which defaults to\nthe model's own filename — so the name a user sees is the\nname of the file they downloaded.\n",
    )
    object: Literal['model']
    created: int | None = Field(
        None, description='Unix timestamp. Model file mtime for local models.'
    )
    owned_by: str | None = Field(
        None,
        description='OpenAI sends an organisation here. We send the provider —\n`local`, or the cloud provider key for a subscription\nbackend.\n',
    )
    x_eugene_plexus: ModelRoutingInfo | None = None


class ChatCompletionRequest(BaseModel):
    model: str = Field(
        ...,
        description='A model id from `GET /v1/models`. The gateway resolves it to\na backend; the client does not choose a backend.\n',
    )
    messages: list[ChatCompletionMessage] = Field(..., min_length=1)
    max_tokens: int | None = Field(
        None,
        description="Maximum output tokens. Filled from the model's settings\nprofile when omitted, then always sent downstream\nexplicitly.\n",
        ge=1,
    )
    temperature: float | None = Field(None, ge=0.0, le=2.0)
    top_p: float | None = Field(None, ge=0.0, le=1.0)
    stop: list[str] | None = Field(None, description='Stop sequences.', max_length=4)
    seed: int | None = Field(
        None,
        description='Passed through to backends that support deterministic\nsampling; dropped with a warning where they do not.\n',
    )
    stream: bool | None = Field(
        False,
        description='When true the response is an SSE stream of\n`ChatCompletionChunk` objects terminated by `data: [DONE]`.\n',
    )
    user: str | None = Field(
        None, description='Opaque client-supplied identifier, echoed into logs only.'
    )


class ChatCompletionResponse(BaseModel):
    id: str = Field(
        ..., description='Completion id, `chatcmpl-` prefixed as clients expect.'
    )
    object: Literal['chat.completion']
    created: int
    model: str = Field(
        ...,
        description='The model that actually served the request. Equal to the\nrequested id in the normal case; after a cascade it names\nwhat answered, which may differ.\n',
    )
    choices: list[ChatCompletionChoice]
    usage: CompletionUsage | None = None
    x_eugene_plexus: CompletionRoutingInfo | None = None


class ChatCompletionChunk(BaseModel):
    """
    One SSE frame of a streaming completion.
    """

    id: str
    object: Literal['chat.completion.chunk']
    created: int
    model: str
    choices: list[ChatCompletionChunkChoice]
    usage: CompletionUsage | None = Field(
        None, description='Present on the final chunk only.'
    )


class DriversInfo(BaseModel):
    drivers: list[DriverHealth] = Field(
        ...,
        description="Per-driver health snapshot, ordered as the gateway's\n`drivers` config declared them.\n",
    )


class ModelList(BaseModel):
    object: Literal['list']
    data: list[Model]
